name: Publish to Docker Images
on:
  release:
    types: [published]
jobs:
  build:
    runs-on: ubuntu-latest
    permissions:
      contents: read
      id-token: write
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - name: Build Docker Images
        uses: philips-software/docker-ci-scripts@v4.5.0
        with:
          dockerfile: .
          image-name: server
          tags: latest v0 v0.1 ${{ github.ref_name }}
          push-branches: main
        env:
          REGISTRY_USERNAME: lil5
          REGISTRY_TOKEN: ${{ secrets.DOCKERHUB_TOKEN }}
          REGISTRY_URL: docker.io
